AllCops:
  Exclude:
    - "spec/**/*"
    - "db/**/*"
    - "lib/generators/templates/landable.rb"

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
