language: ruby
cache: bundler

gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile

env:
  - TEST_SUITE=landable:spec
  - TEST_SUITE=landable:cucumber

matrix:
  include:
    - rvm: 2.3.3
      gemfile: gemfiles/rails_5_0.gemfile
      env: TEST_SUITE=landable:spec
    - rvm: 2.3.3
      gemfile: gemfiles/rails_5_0.gemfile
      env: TEST_SUITE=landable:cucumber
    - rvm: 2.3.3
      gemfile: Gemfile
      env: TEST_SUITE=rubocop

  allow_failures:
    - rvm: 2.1.9
      gemfile: gemfiles/rails_4_0.gemfile
      env: TEST_SUITE=landable:spec

rvm:
  - 2.1.9
  - 2.3.3

before_script:
  - psql -c "CREATE USER dummy WITH superuser" -U postgres
  - psql -c "CREATE DATABASE dummy_test;" -U postgres
script:
  - script/redb
  - bundle exec rake $TEST_SUITE

notifications:
  # let enova know about the build
  slack: enova:xzPNLg3AxkbkUcUlfn7sqHW5
  email: trogdor@enova.com

services:
  - postgresql

secure: "SovzxN4N1XrP1I3jtTQrwSJUI0XZCotr7NkjPTlnk3Zb1/qa/QKpoM3bM64/YFgL33I8BIp2UDAVQj4CnbqqetbG8MfcjNOEmBLF7gHRFMD4NHpFwS9LEwwSdWCnSNXdB0G7gySd5X/dLgQ1fKEaFaacvRhfFTeAr671g5et5RY="
